apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: admission-resource-validate
webhooks:
  - name: im.shimo.admission-resource
    namespaceSelector:
      matchLabels:
        admission-resource: enabled
    rules:
      - apiGroups:   ["apps"]
        apiVersions: ["v1"]
        operations:  ["CREATE"]
        resources:   ["deployments","statefulsets"]
        scope: "Namespaced"
    clientConfig:
      service:
        namespace: default
        name: admission-resource
        path: "/validate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURtakNDQW9LZ0F3SUJBZ0lVWnVuMFVHam5wNGlUTkxxMUVRL1RINzEwNVRnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxjbTVsZEdWek1CNFhEVEl5TURFeE1URTBNamN3TUZvWERUSTNNREV4TURFME1qY3dNRm93WlRFTE1Ba0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbGFVcHBibWN4RERBSwpCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByZFdKbGNtNWxkR1Z6Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBOUFNWitxVWtOekhHclF6WWRqTmgKV2tiSjkweU4vU05MYnliZHJtTDlpYnNBWTdqY2xwbTZUMExVRG1XTTFiaGdPTmxmZFpqSzcvMGYwNUJHc2VzVgowODBRQVdPcmY1dTdsdjNYeFVWSVRqbmFhV1g3OEYyQU1PRm1WRVc2TzJuUVh6dWlyM0JpNkYxcnltQXF0UVp5ClRQK2h3cHlhNmd0ejVCSHEyKzhRY2JnQlU5dUpudE1YNUlnY1Y5MytNa2swOTBYR0l4MmM4SGlmSlgxdnpOblMKU01FTUFXRENIK3dLYTFQWHpqUmNUOGxlSXBQWnBoWEJCYkdrOWx6VDlNa2kxVG4rc0tZUFc0UHRwaUJNSGdrNgpkdU9Wbm1vbEljZ0ZYTDNENDhPY2NRZXUxb0t6K21VNGlvaklDazV6VVgrTUlhb2xnSUVZdFBSZDlQL3hkMkJSCkFRSURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlYKSFE0RUZnUVVoZ3c1NWtLeCtyTTNoWWc1M3M2WUs0emtlK3d3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQU83Ngp6bmN6c0pQSkNyU0ZmM3RFN01UcmN0NXFybzh0Ylk0bFBwcEFTRnE3aThlQU03NkRUUnBDdVU1THphdHB3TmJqClhKbFJ5YWhLYW8xbG1TTWlqRzVOem85UzNuTWJXTll2c2dudmNNSE4zaXVzMmx1U1JvRWR5TDBFNThKR3hiM3UKcnBnRXJaNGhyQitZVWhaRVZFUkRuRzNRbmFPRWpybGFjdWR6MlNVbGZqRFNlYWZPMDFHdVhsTjQ5c3dVMC9LWgpaSklXRUYvanRLTEpkejQzVjU3VStBRlhvWkJJSTQrQmpGNmFJZjN3T1d1MHFZL3cweWVpNGZ0R0NJUUdiY3FiCkV3YURvVmJUcXJScHJmUGZCd2ZtYjZkSWxxaHdBM05ZTkR1WTNIL1JTR0paYXdvNjJTRjZkdityN3lXNVFrTFAKQkg3bld0WjBvR2Z1cHpsZnlDZz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
    admissionReviewVersions: ["v1"]
    sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: admission-resource-mutate
webhooks:
  - name: im.shimo.admission-resource-mutate
    namespaceSelector:
      matchLabels:
        admission-resource: enabled
    clientConfig:
      service:
        namespace: default
        name: admission-resource
        path: "/mutate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURtakNDQW9LZ0F3SUJBZ0lVWnVuMFVHam5wNGlUTkxxMUVRL1RINzEwNVRnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxjbTVsZEdWek1CNFhEVEl5TURFeE1URTBNamN3TUZvWERUSTNNREV4TURFME1qY3dNRm93WlRFTE1Ba0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbGFVcHBibWN4RERBSwpCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByZFdKbGNtNWxkR1Z6Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBOUFNWitxVWtOekhHclF6WWRqTmgKV2tiSjkweU4vU05MYnliZHJtTDlpYnNBWTdqY2xwbTZUMExVRG1XTTFiaGdPTmxmZFpqSzcvMGYwNUJHc2VzVgowODBRQVdPcmY1dTdsdjNYeFVWSVRqbmFhV1g3OEYyQU1PRm1WRVc2TzJuUVh6dWlyM0JpNkYxcnltQXF0UVp5ClRQK2h3cHlhNmd0ejVCSHEyKzhRY2JnQlU5dUpudE1YNUlnY1Y5MytNa2swOTBYR0l4MmM4SGlmSlgxdnpOblMKU01FTUFXRENIK3dLYTFQWHpqUmNUOGxlSXBQWnBoWEJCYkdrOWx6VDlNa2kxVG4rc0tZUFc0UHRwaUJNSGdrNgpkdU9Wbm1vbEljZ0ZYTDNENDhPY2NRZXUxb0t6K21VNGlvaklDazV6VVgrTUlhb2xnSUVZdFBSZDlQL3hkMkJSCkFRSURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlYKSFE0RUZnUVVoZ3c1NWtLeCtyTTNoWWc1M3M2WUs0emtlK3d3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQU83Ngp6bmN6c0pQSkNyU0ZmM3RFN01UcmN0NXFybzh0Ylk0bFBwcEFTRnE3aThlQU03NkRUUnBDdVU1THphdHB3TmJqClhKbFJ5YWhLYW8xbG1TTWlqRzVOem85UzNuTWJXTll2c2dudmNNSE4zaXVzMmx1U1JvRWR5TDBFNThKR3hiM3UKcnBnRXJaNGhyQitZVWhaRVZFUkRuRzNRbmFPRWpybGFjdWR6MlNVbGZqRFNlYWZPMDFHdVhsTjQ5c3dVMC9LWgpaSklXRUYvanRLTEpkejQzVjU3VStBRlhvWkJJSTQrQmpGNmFJZjN3T1d1MHFZL3cweWVpNGZ0R0NJUUdiY3FiCkV3YURvVmJUcXJScHJmUGZCd2ZtYjZkSWxxaHdBM05ZTkR1WTNIL1JTR0paYXdvNjJTRjZkdityN3lXNVFrTFAKQkg3bld0WjBvR2Z1cHpsZnlDZz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments","statefulset"]
        scope: "Namespaced"
    admissionReviewVersions: [ "v1" ]
    sideEffects: None